
```{r setup, include=FALSE} 
knitr::opts_chunk$set(warning = FALSE, message = FALSE) 
```

```{r}
library(tidyverse)
library(data.table)
library(glmmTMB)
library(DHARMa)
library(effects)
library(performance)
library(purrr)
library(furrr)
library(splines)
library(future.apply)
library(broom)
library(dplyr)
library(tidyr)
library(ggplot2)
library(gridExtra)
library(RColorBrewer)
library(plotly) 
library(ggeffects)
```

```{r}
# uploading
speed_limit_treated <- read_csv('../data/output/speed_limit_intervention_table.csv', show_col_types = FALSE)

# meant to handle large datasets
speed_limit_treated <- as.data.table(speed_limit_treated)
```

```{r}
# scale variables
# the odds ratio of these variables will now represent the change in odds for a *one standard deviation* increase in the original predictor.

speed_limit_treated <- speed_limit_treated %>%
  mutate(
    scaled_pop = scale(nyc_metro_pop),
    scaled_summonses = scale(citywide_traffic_summonses),
    scaled_traffic_volume = scale(nyc_metro_dvmt),
    scaled_pop_density = scale(pop_per_sqmi),
    scaled_time = scale(time)
  )
```

# Model 

```{r}
# intersections that solely received citywide speed limit as an intervention

model_sl <- glmmTMB(
  pedestrian_death_or_injury ~
    speed_limit_post +
    covid_2020 +
    scaled_summonses +
    scaled_traffic_volume + 
    ns(scaled_pop_density, df = 2) +
    scaled_time +
    (1 | boro_name/ntaname/intersection_id),
  family = nbinom1,
  data = speed_limit_treated
)

summary(model_sl)
```


```{r}
# diagnostics

sim_res_sl <- simulateResiduals(fittedModel = model_sl, n = 250, plot = TRUE)
testZeroInflation(sim_res_sl) # zero-inflation test
testDispersion(sim_res_sl) # dispersion test
testUniformity(sim_res_sl) # KS test
testOutliers(sim_res_sl) # outliers
```

```{r}
ever_treated_w_sl <- read_csv('../data/output/full_ever_treated_dataset.csv')
ever_treated_w_sl <- ever_treated_w_sl %>%
  mutate(
    scaled_summonses = scale(citywide_traffic_summonses),
    scaled_traffic_volume = scale(nyc_metro_dvmt),
    scaled_pop_density = scale(pop_per_sqmi),
    scaled_time = scale(time)
  )

model_w_sl <- glmmTMB(
  pedestrian_death_or_injury ~ 
    turn_traffic_calming_post +
    leading_pedestrian_interval_post +
    enhanced_crossing_post +
    speed_humps_post +
    street_improvement_project_post +
    street_improvement_corridors_post +
    signal_retiming_post +
    slow_zones_post +
    speed_limit_post +
    covid_2020 + 
    scaled_summonses + 
    scaled_traffic_volume + 
    ns(scaled_pop_density, df = 2) +        
    scaled_time +   
    (1 | boro_name/ntaname/intersection_id),
  family = nbinom1,
  data = ever_treated_w_sl
) 

summary(model_w_sl)
```

```{r}
# diagnostics

sim_res_w_sl <- simulateResiduals(fittedModel = model_w_sl, n = 250, plot = TRUE)
testZeroInflation(sim_res_w_sl) # zero-inflation test
testDispersion(sim_res_w_sl) # dispersion test
testUniformity(sim_res_w_sl) # KS test
testOutliers(sim_res_w_sl) # outliers
```

```{r}
# all intersections, even those never treated (2013-2023)

all_intersections <- read_csv('../data/output/intersection_intervention_table_final.csv')
all_intersections <- all_intersections %>%
  mutate(
    scaled_summonses = scale(citywide_traffic_summonses),
    scaled_traffic_volume = scale(nyc_metro_dvmt),
    scaled_pop_density = scale(pop_per_sqmi),
    scaled_time = scale(time)
  )

model_all <- glmmTMB(
  pedestrian_death_or_injury ~ 
    turn_traffic_calming_post +
    leading_pedestrian_interval_post +
    enhanced_crossing_post +
    speed_humps_post +
    street_improvement_project_post +
    street_improvement_corridors_post +
    signal_retiming_post +
    slow_zones_post +
    speed_limit_post +
    covid_2020 + 
    scaled_summonses + 
    scaled_traffic_volume + 
    ns(scaled_pop_density, df = 2) +        
    scaled_time +   
    (1 | boro_name/ntaname/intersection_id),
  family = nbinom1,
  data = all_intersections %>% filter(all_intersections$year >= 2013 & all_intersections$year <= 2023)
) 

summary(model_all)

```

```{r}
# diagnostics

sim_res_all <- simulateResiduals(fittedModel = model_all, n = 250, plot = TRUE)
testZeroInflation(sim_res_all) # zero-inflation test
testDispersion(sim_res_all) # dispersion test
testUniformity(sim_res_all) # KS test
testOutliers(sim_res_all) # outliers
```

