
```{r setup, include=FALSE} 
knitr::opts_chunk$set(warning = FALSE, message = FALSE) 
```

```{r}
library(tidyverse)
library(data.table)
library(glmmTMB)
library(DHARMa)
library(effects)
library(performance)
library(purrr)
library(furrr)
library(splines)
library(future.apply)
library(broom)
library(dplyr)
library(tidyr)
library(ggplot2)
library(gridExtra)
library(RColorBrewer)
library(plotly) 
library(ggeffects)
```

# Mode: 2013-2016, no non-speed limit treatments

```{r}
ever_treated_w_sl_2013_2016 <- read_csv('../data/output/intersection_intervention_table_untreated_2013-2016.csv')
ever_treated_w_sl_2013_2016 <- ever_treated_w_sl_2013_2016 %>%
  mutate(
    scaled_summonses = scale(citywide_traffic_summonses),
    scaled_traffic_volume = scale(nyc_metro_dvmt),
    scaled_pop_density = scale(pop_per_sqmi),
    scaled_time = scale(time)
  )

model_w_sl <- glmmTMB(
  pedestrian_death_or_injury ~ 
    # turn_traffic_calming_post +
    # leading_pedestrian_interval_post +
    # enhanced_crossing_post +
    # speed_humps_post +
    # street_improvement_project_post +
    # street_improvement_corridors_post +
    # signal_retiming_post +
    # slow_zones_post +
    speed_limit_post +
    #covid_2020 + 
    #scaled_summonses + 
    scaled_traffic_volume + 
    ns(scaled_pop_density, df = 2) +        
    #scaled_time + 
    source +
    (1 | intersection_id),
  family = nbinom1,
  data = ever_treated_w_sl_2013_2016
) 

summary(model_w_sl)
```

```{r}
# Get the confidence intervals for the log-coefficients
ci_log <- confint(model_w_sl, parm = "beta_", method = "wald") # Wald is fastest

# Get the coefficients table from the summary
summary_table <- summary(model_w_sl)$coefficients$cond

# Combine the log-estimates and log-CIs
log_results <- cbind(summary_table, ci_log)

# Exponentiate everything to get IRRs and their CIs
irr_results <- exp(log_results)

# Print the final table
print(irr_results)
```

```{r}
# diagnostics

sim_res_sl <- simulateResiduals(fittedModel = model_w_sl, n = 250, plot = TRUE)
testZeroInflation(sim_res_sl) # zero-inflation test
testDispersion(sim_res_sl) # dispersion test
testUniformity(sim_res_sl) # KS test
testOutliers(sim_res_sl) # outliers
```

```{r}
check_collinearity(model_w_sl)
```

# Mode: 2013-2023, no non-speed limit treatments

```{r}
ever_treated_w_sl_2013_2023 <- read_csv('../data/output/intersection_intervention_table_untreated_2013-2023.csv')
ever_treated_w_sl_2013_2023 <- ever_treated_w_sl_2013_2023 %>%
  mutate(
    scaled_summonses = scale(citywide_traffic_summonses),
    scaled_traffic_volume = scale(nyc_metro_dvmt),
    scaled_pop_density = scale(pop_per_sqmi),
    scaled_time = scale(time)
  )

model_w_sl_2 <- glmmTMB(
  pedestrian_death_or_injury ~ 
    # turn_traffic_calming_post +
    # leading_pedestrian_interval_post +
    # enhanced_crossing_post +
    # speed_humps_post +
    # street_improvement_project_post +
    # street_improvement_corridors_post +
    # signal_retiming_post +
    # slow_zones_post +
    speed_limit_post +
    covid_2020 + 
    scaled_summonses + 
    scaled_traffic_volume + 
    ns(scaled_pop_density, df = 2) +        
    scaled_time +   
    source +
    (1 | intersection_id),
  family = nbinom1,
  data = ever_treated_w_sl_2013_2023
) 

summary(model_w_sl_2)
```

```{r}
# Get the confidence intervals for the log-coefficients
ci_log <- confint(model_w_sl_2, parm = "beta_", method = "wald") # Wald is fastest

# Get the coefficients table from the summary
summary_table <- summary(model_w_sl_2)$coefficients$cond

# Combine the log-estimates and log-CIs
log_results <- cbind(summary_table, ci_log)

# Exponentiate everything to get IRRs and their CIs
irr_results <- exp(log_results)

# Print the final table
print(irr_results)
```

```{r}
# diagnostics

sim_res_sl_2 <- simulateResiduals(fittedModel = model_w_sl_2, n = 250, plot = TRUE)
testZeroInflation(sim_res_sl_2) # zero-inflation test
testDispersion(sim_res_sl_2) # dispersion test
testUniformity(sim_res_sl_2) # KS test
testOutliers(sim_res_sl_2) # outliers
```

```{r}
check_collinearity(model_w_sl_2)
```

----------------------------------------------------------------------------------------

# BELOW MODELS ARE NOT INCLUDED IN PAPER!

# Mode: 2013-2023, ONLY speed limit treatments

```{r}
ever_treated_w_sl_only_2013_2023 <- read_csv('../data/output/intersection_table_speed_limit_only_2013-2023.csv')
ever_treated_w_sl_only_2013_2023 <- ever_treated_w_sl_only_2013_2023 %>%
  mutate(
    scaled_summonses = scale(citywide_traffic_summonses),
    scaled_traffic_volume = scale(nyc_metro_dvmt),
    scaled_pop_density = scale(pop_per_sqmi),
    scaled_time = scale(time)
  )

model_only_sl <- glmmTMB(
  pedestrian_death_or_injury ~ 
    # turn_traffic_calming_post +
    # leading_pedestrian_interval_post +
    # enhanced_crossing_post +
    # speed_humps_post +
    # street_improvement_project_post +
    # street_improvement_corridors_post +
    # signal_retiming_post +
    # slow_zones_post +
    speed_limit_post +
    covid_2020 + 
    scaled_summonses + 
    scaled_traffic_volume + 
    ns(scaled_pop_density, df = 2) +        
    scaled_time +   
    (1 | ntaname/intersection_id),
  family = nbinom1,
  data = ever_treated_w_sl_only_2013_2023
) 

summary(model_only_sl)
```

```{r}
# diagnostics

sim_res_only_sl <- simulateResiduals(fittedModel = model_only_sl, n = 250, plot = TRUE)
testZeroInflation(sim_res_only_sl) # zero-inflation test
testDispersion(sim_res_only_sl) # dispersion test
testUniformity(sim_res_only_sl) # KS test
testOutliers(sim_res_only_sl) # outliers
```

```{r}
check_collinearity(model_only_sl)
```

# Mode: 2013-2016, ONLY speed limit treatments

```{r}
ever_treated_w_sl_only_2013_2016 <- read_csv('../data/output/intersection_table_speed_limit_only_2013-2016.csv')
ever_treated_w_sl_only_2013_2016 <- ever_treated_w_sl_only_2013_2016 %>%
  mutate(
    scaled_summonses = scale(citywide_traffic_summonses),
    scaled_traffic_volume = scale(nyc_metro_dvmt),
    scaled_pop_density = scale(pop_per_sqmi),
    scaled_time = scale(time)
  )

model_only_sl_2 <- glmmTMB(
  pedestrian_death_or_injury ~ 
    # turn_traffic_calming_post +
    # leading_pedestrian_interval_post +
    # enhanced_crossing_post +
    # speed_humps_post +
    # street_improvement_project_post +
    # street_improvement_corridors_post +
    # signal_retiming_post +
    # slow_zones_post +
    speed_limit_post +
    #covid_2020 + 
    #scaled_summonses + 
    scaled_traffic_volume + 
    ns(scaled_pop_density, df = 2) +        
    #scaled_time +   
    (1 | intersection_id),
  family = nbinom1,
  data = ever_treated_w_sl_only_2013_2016
) 

summary(model_only_sl_2)
```

```{r}
# diagnostics

sim_res_only_sl_2 <- simulateResiduals(fittedModel = model_only_sl_2, n = 250, plot = TRUE)
testZeroInflation(sim_res_only_sl_2) # zero-inflation test
testDispersion(sim_res_only_sl_2) # dispersion test
testUniformity(sim_res_only_sl_2) # KS test
testOutliers(sim_res_only_sl_2) # outliers
```

```{r}
check_collinearity(model_only_sl_2)
```
















